<html>
    <head>
        <meta charset="utf-8">
        <title>$status$</title>
        <script type="text/javascript" src="$base$utterlyidle/rendering/matchFailure.js"></script>
        <link rel="stylesheet" href="$base$utterlyidle/rendering/style.css" type="text/css"/>
    </head>
<body>
    <h1>$status$</h1>
    <p>Did you mean one of these?</p>

    <ul class="resources">
        $resources:{ <li class="resource">$(it.method)(resource=it)$</li> }$
    </ul>

</body>
</html>